# Generated by Django 5.1.6 on 2025-06-20 02:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MedicineInventory',
            fields=[
                ('product_id', models.IntegerField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(blank=True, max_length=45, null=True)),
                ('unit', models.CharField(blank=True, max_length=45, null=True)),
                ('product_price', models.IntegerField(blank=True, null=True)),
                ('unit_type', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'products',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.IntegerField(primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=45)),
                ('total_quantity', models.IntegerField()),
                ('total_price', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'order',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OrderDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(blank=True, max_length=45, null=True)),
                ('quantity', models.IntegerField()),
            ],
            options={
                'db_table': 'order_details',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='inventory.medicineinventory')),
            ],
            options={
                'db_table': 'cart',
                'managed': False,
            },
        ),
    ]
